name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Telegram Action
        uses: xinthink/action-telegram@v1.1
        with:
          # Используйте секреты GitHub для токена и ID чата
          botToken: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chatId: ${{ secrets.TELEGRAM_CHAT_ID }}
          # Опциональные параметры (раскомментируйте при необходимости):
          # jobStatus: ${{ job.status }}
          # skipSuccess: false
