name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Notify Telegram
  # You may pin to the exact commit or the version.
  # uses: yanzay/notify-telegram@1025564e15f68b2fcddeba37b5bfaf4033c79448
        uses: yanzay/notify-telegram@v0.1.0
        with:
          chat: "-1002355425730"
          token: "7848898742:AAHdVwYYnxaRxQYuEyg4fb2HLHIwO5otEKg"
